[versions]
kotlin = "1.5.21"
mokoMvvm = "0.11.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin.stdlib-common", version.ref = "kotlin" }
mokoMvvmCore = { module = "dev.icerock.moko:mvvm-core", version.ref = "mokoMvvm" }